### ISSUE TITLE
Display fractional values with AngularJS

### ISSUE THREAD

**Issue by lili1725** [bandraszyk/awesome-rating#2]
I can figure out how to display fractional values with AngularJs.
I tried to display the value 1.3.
Here is my code : 

Controller :
        $scope.rate = 1.3;
        $scope.options = {
            readonly: true,
            allowFractional: true
        };

View:
![capture du 2015-04-02 11 18 21](https://cloud.githubusercontent.com/assets/6737423/6961301/054d952e-d92a-11e4-90fe-dd7fa3cea126.png)

Css:
.awesomeRating {
    > .rating-star {
        font-size: 1.5em;
    }
    > .rating-star-fractional {
        font-size: 1.5em;
    }
}

Result : 
![capture du 2015-04-02 10 59 32](https://cloud.githubusercontent.com/assets/6737423/6961014/ae39965e-d927-11e4-993b-e1169b7a2035.png)
![capture du 2015-04-02 11 00 00](https://cloud.githubusercontent.com/assets/6737423/6961015/ae39f130-d927-11e4-8c94-3a5723255691.png)
![capture du 2015-04-02 11 12 36](https://cloud.githubusercontent.com/assets/6737423/6961184/3b3019f6-d929-11e4-8398-3c73ce0febeb.png)
![capture du 2015-04-02 11 12 44](https://cloud.githubusercontent.com/assets/6737423/6961183/3b2e24d4-d929-11e4-9eb8-bc39d08dd6ac.png)

Did I miss something ?
Thanks in advance

**Comment by lili1725** [comment]
My bad, I forgot to include awesomeRating.css in my project. Sorry for that. It works perfectly now.

**Comment by bandraszyk** [comment]
I'm glad it works. Maybe I should highlight the information about the css - I will make an update of readme file then.

**Comment by bandraszyk** [comment]
@lili1725 I have committed the information about styling so it's available in the readme file now, it's more clear for the developer that he or she should link the styles as well. Thanks for your contribution, I hope you like the library.
